builds:
- binary: monkey
  env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '(?i)\breadme\b'
    - '(?i)\bsmall\b'
brews:
  -
    name: monkey
    github:
      owner: bradford-hamilton
      name: homebrew-monkey
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    description: "https://github.com/bradford-hamilton/monkey-lang."
    dependencies:
      - git
      - zsh
    install: |
      bin.install "monkey"
